---
name: Test newly built images

on:
    workflow_call:
        inputs:
            runsOn:
                description: GitHub Actions Runner image
                required: true
                type: string
            images:
                description: Images built in build step
                required: true
                type: string
            target:
                description: Target image for testing
                required: false
                type: string
            integration:
                description: Run integration tests
                required: false
                type: boolean

jobs:

    test:
        name: ${{ inputs.integration && inputs.runsOn || inputs.target }}
        runs-on: ${{ inputs.runsOn }}
        timeout-minutes: 20

        steps:

            - name: Checkout Repo ⚡️
              uses: actions/checkout@v4

            - name: Login to GitHub Container Registry 🔑
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

